inner:
  - Positive_Affect
  - Self_Efficacy
  - Agrreableness
  - Openness
  - Conscientiousness
  - Neuroticism
  - Extraversion

outer:
  - Friendship
  - Loneliness
  - Perceived_Hostility
  - Perceived_Rejection
  - Emotional_Support
  - Instrumental_Support
  - Perceived_Stress
