colors:
  inner: "#3498db"
  outer: "#e67e22"

inner:
  - Positive_Affect
  - Self_Efficacy
  - Agreeableness
  - Openness
  - Conscientiousness
  - Neuroticism
  - Extraversion

outer:
  - Friendship
  - Loneliness
  - Perceived_Hostility
  - Perceived_Rejection
  - Emotional_Support
  - Instrumental_Support
  - Perceived_Stress
