figure:
  figsize: [16, 8]
font:
  size: 22
  family: serif
  serif: ["Times New Roman", "Times"]
axes:
  titlesize: 24
  labelsize: 24
xtick:
  labelsize: 22
ytick:
  labelsize: 22
legend:
  fontsize: 20
  title_fontsize: 22
lines:
  markersize: 18
  linewidth: 3
text:
  usetex: true
  latex:
    preamble: |
      \usepackage{mathptmx}
      \usepackage{textcomp}
